<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <RootNamespace>LabPlot.Core.Wpf</RootNamespace>
    <AssemblyName>LabPlot.Core.Wpf</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LabPlot.Core\LabPlot.Core.csproj" />
  </ItemGroup>

</Project>
