<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>LabPlot.Viewer.Avalonia</RootNamespace>
    <AssemblyName>LabPlot.Viewer.Avalonia</AssemblyName>
    <Version>1.4.1</Version>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LabPlot.Core\LabPlot.Core.csproj" />
    <ProjectReference Include="..\LabPlot.Core.Avalonia\LabPlot.Core.Avalonia.csproj" />
    <ProjectReference Include="..\LabPlot.Viewer\DataViewer.Core\DataViewer.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.14" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.14" />
    <PackageReference Include="ScottPlot.Avalonia" Version="5.1.58" />
  </ItemGroup>
</Project>
